#!/bin/sh

cecho(){
    RED="\033[0;31m"
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'`在这里插入代码片`
    # ... ADD MORE COLORS
    NC='\033[0m' # No Color

    printf "${!1}${2} ${NC}\n"
}

showFailMsg(){
	cecho "RED"  "The prefix can only be feat、docs、fix、style、refactor、test、chore. Don't forget the colon(:)"
	showPrefixMsg
	showExampleMsg
}

showPrefixMsg(){
	echo "Allowed prefix:"
	echo "  feat 开发新需求，必须带上 xxx 信息"
	echo "  fix 修复 bug 使用，必须带上 xxx 信息"
	echo "  docs 修改文档"
	echo "  style 代码格式相关，低频使用"
	echo "  refactor 代码重构(体积优化等等)"
	echo "  test 修改非生产环境代码，如添加测试用例和修改测试代码"
	echo "  chore 修改 bazel 配置相关"
	echo "  coding 临时代码，为了出包，review 的时候禁止合入"
}

showExampleMsg(){
	cecho "GREEN"  "Usage example:"
	echo "	feat(danmaku): Add danmaku list xxx "
	echo "	fix(*): Fix base request timeout error xxx"
	echo "	docs: Add schema useage demo"
}

commit_msg=$(cat "${1:?Missing commit message file}")
valid=0
if [[ $commit_msg =~ ^(((feat)|(docs)|(fix)|(style)|(refactor)|(test)|(chore)|(coding))(\(.*\))?:){1} ]]; then
	if [[ $commit_msg =~ ^(((feat)|(fix))(\(.*\))?:){1} ]]; then
		if [[ ! $commit_msg =~ ((--story=[0-9]+)|(--task=[0-9]+)|(--bug=[0-9]+))+ ]]; then
			cecho "RED"  "请带上 xxx 相关信息!!!!!!"
			showPrefixMsg
			showExampleMsg
			exit 1
		elif [[ ! $commit_msg =~ (--user=){1} ]]; then
			cecho "RED"   "请带上 xxx 相关信息 !!!!!!"
			showPrefixMsg
			showExampleMsg
			exit 1
		else
			exit 0
		fi
	else
		exit 0
	fi
else
	showFailMsg
	exit 1
fi


